[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "intelligent-expense-tracker"
version = "0.1.0"
authors = [
  { name = "Gauransh Arora" },
]
description = "UCS503 Software Engineering - Intelligent Expense Tracker"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: POSIX",
]
dependencies = []

[project.urls]
Homepage = "https://github.com/tiet-ucs503/ucs503p-202627odd-template"
Issues = "https://github.com/tiet-ucs503/ucs503p-202627odd-template/issues"

[tool.pytest.ini_options]
pythonpath = [
  "code"
]